version: "3.7"
services:
  tezos:
    container_name: tezos
    build:
      context: ./
      dockerfile: Dockerfile.dev
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    networks:
      - tezos
networks:
  tezos:
